### PR TITLE
Create appendfile

### PR DESCRIPTION
**Pull request by Varsha-PGDAV**

### CODE REVIEW

**Review by HemantSachdeva — DISMISSED** [review]
Can you add the book.txt too for more clarification of others :)

**Review by Varsha-PGDAV — COMMENTED** [review]
https://drive.google.com/file/d/1HvGA_wS80dQnxpiDsenNknCKJWST5glj/view?usp=sharing

IT IS PHOTO OF THE PROGRAM

**Comment by Varsha-PGDAV** [comment]
https://drive.google.com/file/d/1HvGA_wS80dQnxpiDsenNknCKJWST5glj/view?usp=sharing

IT IS PHOTO OF THE PROGRAM

**Comment by HemantSachdeva** [comment]
> https://drive.google.com/file/d/1HvGA_wS80dQnxpiDsenNknCKJWST5glj/view?usp=sharing
> 
> IT IS PHOTO OF THE PROGRAM

There's no need to provide pic of the program.
I was just asking for the book.txt file which is appended. 
It's ok if you can not push it for some xyz reason.

[INFO] Make photo permissions public to let people view it.

**Pull request closed without merging**
